### ISSUE TITLE
Specify license 

### ISSUE THREAD

**Issue by Richard87** [elliotforbes/angular-2-admin#2]
Would love to know what license you have in mind for this project! 

Richard

**Comment by elliotforbes** [comment]
Added the MIT License! Feel free to do whatever you want with this project! :)

**Comment by Richard87** [comment]
Great,  thanks! Looking forward to looking closer at it! 😀

Den fre. 23. des. 2016, 16:28 skrev Elliot Forbes <notifications@github.com
